id = "passport01"
name = "Solarpass"

bind = "0.0.0.0:8003"
grpc_bind = "0.0.0.0:7003"
domain = "id.solsynth.dev"

templates_dir = "templates"
locales_dir = "locales"

frontend_app = "https://solsynth.dev"

content_endpoint = "https://usercontent.solsynth.dev"

default_user_group = 1

use_registration_magic_token = false

nexus_addr = "localhost:7001"

[debug]
database = false
print_routes = false

[security]
access_token_duration = 3000
refresh_token_duration = 2592000
public_key = "keys/public_key.pem"
private_key = "keys/private_key.pem"
internal_public_key = "keys/internal_public_key.pem"
